---
  - hosts: localhost
    tasks:

      - name: Install git
        become: yes
        package:
          name:
            - git
          state: present

      - name: Install yay
        become: yes
        package:
          name:
            - yey
          state: present

      - name: Download Dotconfig repo
        git:
          repo: https://github.com/NotoriousBIT/Dotfiles.git
          dest: "{{ ansible_env.HOME }}/git/Dotfiles"

      - name: Set keyboard layout DE
        become: yes
        file:
          src: "{{ ansible_env.HOME }}/git/Dotfiles/etc/X11/xorg.conf.d/20-keyboard.conf"
          dest: /etc/X11/xorg.conf.d/20-keyboard.conf
          state: link
          force: yes

      - name: Install audio software
        become: yes
        package:
          name:
            - pulseaudio
            - pavucontrol
          state: present

      - name: Install video software
        become: yes
        package:
          name:
            - nvidia
            - nvidia-settings
          state: present

      - name: Install network software
        become: yes
        package:
          name:
            - nm-connection-editor
          state: present

      - name: Install go
        become: yes
        package:
          name:
            - go
          state: present

      - name: Install xorg
        become: yes
        package:
          name:
            - xorg
            - xorg-drivers
            - xorg-xinit
          state: present

      - name: Install light-dm
        become: yes
        package:
          name:
            - lightdm
            - lightdm-gtk-greeter
            - lightdm-webkit2-greeter
            - light-locker
          state: present

      - name: Install theme litarvan
        become: yes
        package:
          name:
            - lightdm-webkit-theme-litarvan
          state: present
          use: yay

      - name: Enable service lightdm and ensure it is not masked
        systemd:
          name: lightdm
          enabled: yes
          masked: no

      - name: Set lightdm config
        become: yes
        file:
          src: "{{ ansible_env.HOME }}/git/Dotfiles/etc/lightdm/lightdm.conf"
          dest: /etc/lightdm/lightdm.conf
          state: link
          force: yes

      - name: Set lightdm-webkit2-greeter config
        become: yes
        file:
          src: "{{ ansible_env.HOME }}/git/Dotfiles/etc/lightdm/lightdm-webkit2-greeter.conf"
          dest: /etc/lightdm/lightdm-webkit2-greeter.conf
          state: link
          force: yes

      - name: Install awesome
        become: yes
        package:
          name:
            - awesome
          state: present



          #!/bin/bash




# ###########################
# # GIT
# ###########################
# pacman -S --noconfirm git
# mkdir git
# chown --recursive $SUDO_USER: git

# ###########################
# # YAY
# ###########################
# pacman -S --noconfirm git go
# rm -rf yay
# git clone https://aur.archlinux.org/yay.git
# chown $SUDO_USER: yay
# (cd yay && su $SUDO_USER -c "makepkg -s")
# (cd yay && pacman -U --noconfirm *.pkg.tar.*)
# rm -rf yay

# ###########################
# # FONTS
# ###########################
# pacman -S --noconfirm ttf-opensans ttf-ubuntu-font-family awesome-terminal-fonts powerline-fonts

# ###########################
# # KEYBOARD LAYOUT DE
# ###########################
# echo 'Section "InputClass"' > /etc/X11/xorg.conf.d/20-keyboard.conf
# echo '       Identifier "keyboard"' >> /etc/X11/xorg.conf.d/20-keyboard.conf
# echo '       MatchIsKeyboard "yes"' >> /etc/X11/xorg.conf.d/20-keyboard.conf
# echo '       Option "XkbLayout" "de"' >> /etc/X11/xorg.conf.d/20-keyboard.conf
# echo '       Option "XkbVariant" "nodeadkeys"' >> /etc/X11/xorg.conf.d/20-keyboard.conf
# echo 'EndSection' >> /etc/X11/xorg.conf.d/20-keyboard.conf

# ###########################
# # LIGHTDM GREETER
# ###########################
# pacman -S --noconfirm lightdm lightdm-webkit2-greeter light-locker

# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/helper/lightdm/lightdm.conf -O /etc/lightdm/lightdm.conf
# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/helper/lightdm/lightdm-webkit2-greeter.conf -O /etc/lightdm/lightdm-webkit2-greeter.conf

# # AETHER THEME
# pacman -S --noconfirm git ttf-opensans
# rm -rf lightdm-webkit-theme-aether
# git clone https://aur.archlinux.org/lightdm-webkit-theme-aether.git
# chown $SUDO_USER: lightdm-webkit-theme-aether
# (cd lightdm-webkit-theme-aether && su $SUDO_USER -c "makepkg -s")
# (cd lightdm-webkit-theme-aether && pacman -U --noconfirm *.pkg.tar.*)
# rm -rf lightdm-webkit-theme-aether

# systemctl enable lightdm


# ###########################
# # TERMITE
# ###########################
# pacman -S --noconfirm termite

# mkdir -p /home/$SUDO_USER/.config/termite
# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.config/termite/config -O /home/$SUDO_USER/.config/termite/config

# chown --recursive $SUDO_USER: .config

# ###########################
# # ZSH
# ###########################
# pacman -S --noconfirm zsh ttf-ubuntu-font-family

# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.zshrc -O /home/$SUDO_USER/.zshrc
# chown --recursive $SUDO_USER: .zshrc

# # POWERLEVEL10K
# (cd git && git clone https://github.com/romkatv/powerlevel10k.git)
# chown --recursive $SUDO_USER: .git

# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.p10k.zsh -O /home/$SUDO_USER/.p10k.zsh
# chown --recursive $SUDO_USER: .p10k.zsh

# chsh -s $(which zsh) $SUDO_USER

# ###########################
# # NITROGEN
# ###########################
# pacman -S --noconfirm nitrogen

# git clone https://github.com/NotoriousBIT/arch-install-script.git
# mv ./arch-install-script/wallpaper ./wallpaper
# chown --recursive $SUDO_USER: wallpaper
# rm -rf arch-install-script

# mkdir -p /home/$SUDO_USER/.config/nitrogen
# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.config/nitrogen/bg-saved.cfg -O /home/$SUDO_USER/.config/nitrogen/bg-saved.cfg
# chown --recursive $SUDO_USER: .config

# ###########################
# # COMPTON
# ###########################
# pacman -S --noconfirm picom # compton

# mkdir -p /home/$SUDO_USER/.config/picom
# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.config/picom/picom.conf -O /home/$SUDO_USER/.config/picom/picom.conf
# chown --recursive $SUDO_USER: .config

# ###########################
# # EXA - ls replacement
# ###########################
# pacman -S --noconfirm exa

# ###########################
# # VIM
# ###########################
# git clone https://github.com/VundleVim/Vundle.vim.git /home/$SUDO_USER/.vim/bundle/Vundle.vim
# chown --recursive $SUDO_USER: .vim

# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.vimrc -O /home/$SUDO_USER/.vimrc
# chown --recursive $SUDO_USER: .vimrc

# (su $SUDO_USER && vim -c 'PluginInstall' -c 'qa!')

# ###########################
# # VIFM
# ###########################
# pacman -S --noconfirm vifm

# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.Xresources -O /home/$SUDO_USER/.Xresources
# chown --recursive $SUDO_USER: .Xresources

