---
  - hosts: localhost
    roles:
      - kewlfft.aur
    tasks:

      - name: Install git
        become: yes
        package:
          name:
            - git
          state: present

      - name: Download yay
        git:
          repo: https://aur.archlinux.org/yay.git
          dest: "{{ ansible_env.HOME }}/git/yay"

      - name: Install yay
        shell:
          cmd: makepkg -isf --noconfirm
          chdir: "{{ ansible_env.HOME }}/git/yay"

      # - name: Install yay
      #   become: yes
      #   shell:
      #     cmd: pacman -U *.pkg.tar.zst --noconfirm
      #     chdir: "{{ ansible_env.HOME }}/git/yay"

      - name: Download Dotconfig repo
        git:
          repo: https://github.com/NotoriousBIT/Dotfiles.git
          dest: "{{ ansible_env.HOME }}/git/Dotfiles"

      - name: Link .config
        file:
          src: "{{ ansible_env.HOME }}/git/Dotfiles/.config"
          dest: "{{ ansible_env.HOME }}/.config"
          state: link
          force: yes

      - name: Install audio software
        become: yes
        package:
          name:
            - pulseaudio
            - pavucontrol
          state: present

      - name: Install video software
        become: yes
        package:
          name:
            - nvidia-lts
            - nvidia-settings
          state: present

      - name: Install network software
        become: yes
        package:
          name:
            - nm-connection-editor
          state: present

      - name: Install go
        become: yes
        package:
          name:
            - go
          state: present

      - name: Install xorg
        become: yes
        package:
          name:
            - xorg
            - xorg-drivers
            - xorg-xinit
          state: present

      - name: Set keyboard layout DE
        become: yes
        copy:
          src: "{{ ansible_env.HOME }}/git/Dotfiles/etc/X11/xorg.conf.d/20-keyboard.conf"
          dest: /etc/X11/xorg.conf.d/20-keyboard.conf
          force: yes

      - name: Install light-dm
        become: yes
        package:
          name:
            - lightdm
            - lightdm-gtk-greeter
            - lightdm-webkit2-greeter
            - light-locker
          state: present

      - name: Install theme litarvan
        become: yes
        aur:
          name:
            - lightdm-webkit-theme-litarvan
          state: present
          use: yay

      - name: Enable service lightdm and ensure it is not masked
        become: yes
        systemd:
          name: lightdm
          enabled: yes
          masked: no

      - name: Set lightdm config
        become: yes
        copy:
          src: "{{ ansible_env.HOME }}/git/Dotfiles/etc/lightdm/lightdm.conf"
          dest: /etc/lightdm/lightdm.conf
          force: yes

      - name: Set lightdm-webkit2-greeter config
        become: yes
        copy:
          src: "{{ ansible_env.HOME }}/git/Dotfiles/etc/lightdm/lightdm-webkit2-greeter.conf"
          dest: /etc/lightdm/lightdm-webkit2-greeter.conf
          force: yes

      - name: Install awesome
        become: yes
        package:
          name:
            - awesome
          state: present

      - name: Install dmenu
        become: yes
        package:
          name:
            - dmenu
          state: present

      - name: Install Alacritty
        become: yes
        package:
          name:
            - alacritty
          state: present

      - name: Install Picom
        become: yes
        package:
          name:
            - picom
          state: present

      - name: Install nitrogen
        become: yes
        package:
          name:
            - nitrogen
          state: present

      - name: Install zsh
        become: yes
        package:
          name:
            - zsh
          state: present

      - name: Link .zshrc
        file:
          src: "{{ ansible_env.HOME }}/git/Dotfiles/.zshrc"
          dest: "{{ ansible_env.HOME }}/.zshrc"
          state: link
          force: yes

      - name: Set default shell to zsh
        become: yes
        shell:
          cmd: "chsh -s $(which zsh) {{ lookup('env', 'USER') }}"

      - name: Install zsh-theme-powerlevel10k
        # become: yes
        aur:
          name:
            - zsh-theme-powerlevel10k-git
            - ttf-font-awesome
            - ttf-meslo-nerd-font-powerlevel10k
          state: present
          use: yay

      - name: Link .p10k.zsh
        file:
          src: "{{ ansible_env.HOME }}/git/Dotfiles/.p10k.zsh"
          dest: "{{ ansible_env.HOME }}/.p10k.zsh"
          state: link
          force: yes

      - name: Install wifi drivers
        aur:
          name:
            - rtl8821ce-dkms-git
          state: present
          use: yay

      # Some new Yoga laptops (like the Yoga 530) come with rtl8821ce as the Wi-Fi/Bluetooth chip. But the ideapad-laptop module, which may come included in your distribution, may conflict with this driver. To disable:
      - name: Disable ideapad_laptop
        become: yes
        shell:
          cmd: modprobe -r ideapad_laptop

      - name: Install dialog
        become: yes
        package:
          name:
            - dialog
          state: present




# ###########################
# # FONTS
# ###########################
# pacman -S --noconfirm ttf-opensans ttf-ubuntu-font-family awesome-terminal-fonts powerline-fonts

# chown --recursive $SUDO_USER: .config

# ###########################
# # ZSH
# ###########################
# pacman -S --noconfirm zsh ttf-ubuntu-font-family

# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.zshrc -O /home/$SUDO_USER/.zshrc
# chown --recursive $SUDO_USER: .zshrc

# # POWERLEVEL10K
# (cd git && git clone https://github.com/romkatv/powerlevel10k.git)
# chown --recursive $SUDO_USER: .git

# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.p10k.zsh -O /home/$SUDO_USER/.p10k.zsh
# chown --recursive $SUDO_USER: .p10k.zsh

# chsh -s $(which zsh) $SUDO_USER

# ###########################
# # NITROGEN
# ###########################
# pacman -S --noconfirm nitrogen

# git clone https://github.com/NotoriousBIT/arch-install-script.git
# mv ./arch-install-script/wallpaper ./wallpaper
# chown --recursive $SUDO_USER: wallpaper
# rm -rf arch-install-script

# mkdir -p /home/$SUDO_USER/.config/nitrogen
# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.config/nitrogen/bg-saved.cfg -O /home/$SUDO_USER/.config/nitrogen/bg-saved.cfg
# chown --recursive $SUDO_USER: .config

# ###########################
# # EXA - ls replacement
# ###########################
# pacman -S --noconfirm exa

# ###########################
# # VIM
# ###########################
# git clone https://github.com/VundleVim/Vundle.vim.git /home/$SUDO_USER/.vim/bundle/Vundle.vim
# chown --recursive $SUDO_USER: .vim

# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.vimrc -O /home/$SUDO_USER/.vimrc
# chown --recursive $SUDO_USER: .vimrc

# (su $SUDO_USER && vim -c 'PluginInstall' -c 'qa!')

# ###########################
# # VIFM
# ###########################
# pacman -S --noconfirm vifm

# wget -N https://raw.githubusercontent.com/NotoriousBIT/arch-install-script/master/configs/.Xresources -O /home/$SUDO_USER/.Xresources
# chown --recursive $SUDO_USER: .Xresources

